### PR TITLE
Throw ResponseError type when an error occurs

### PR DESCRIPTION
**Pull request by EricPaquetB**

### CODE REVIEW

**Comment by mcote01** [comment]
`@bentley/itwin-client` package seems to have been removed recently according to this pr https://github.com/iTwin/itwinjs-core/pull/3021

https://github.com/iTwin/itwinjs-core/pull/3021

**Comment by mcote01** [comment]
`@bentley/itwin-client` has been removed according to this [PR #3021](https://github.com/iTwin/itwinjs-core/pull/3021)

@bentley refers to imodeljs. Need to find a replacement for `ResponseError` used in iTwin

**Comment by mcote01** [comment]
I would expect changes in package.json and package-lock.json if new dependencies are used, and a version bump should be there too

**Review by MarcBedard8 — CHANGES_REQUESTED** [review]
I think you should use async/await and try catch block instead of then/catch.
Don't use @bentley/itwin-client.

**Comment by mcote01** [comment]
run `npm i` to automatically update package-lock.json and commit changes when `package.json` contains changes

**Review by MarcBedard8 — APPROVED** [review]
Look good to me.
I think you might want to add the @throw documentation param to your methods documentation.
   * @throws [[BentleyError]] if somehting blablabla

**Review by MarcBedard8 — APPROVED** [review]

**Review by mcote01 — APPROVED** [review]

**Pull request merged**
