### PR TITLE
Move package core-bentley to normal dependencies.

### PR DESCRIPTION
**Pull request by EricPaquetB**
Move package core-bentley to normal dependencies.
Uniformize error handling.

### CODE REVIEW

**Review by MarcBedard8 — APPROVED** [review]

**Review by mcote01 — APPROVED** [review]

**Comment by aruniverse** [comment]
@EricPaquetB core-bentley shouldve been added as a peer dep

**Comment by EricPaquetB** [comment]
@aruniverse , for which reason ? The way I understand peer dependencies, core-bentley is not one; it is a direct dependency. It would be a peer dependency if it was a host hosting a reality-data-client "plugin" ... ?

**Comment by aruniverse** [comment]
> @aruniverse , for which reason ? 

Typically a bad idea to have a direct dep on a pkg if it uses statics and the usage isn't pure. Sicne you're returning instances of BentleyError, there might be collisions with BentleyError from other versions (even patches). I think it's best to make core-bentley here a dev+peer. I will review again tomorrow morning to make sure if its safe or not to do so.

**Comment by calebmshafer** [comment]
@EricPaquetB @MarcBedard8 @aruniverse this change should have been a minor version bump to go to `0.8.0` since this is a breaking change.

**Pull request merged**
